apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-pruebas-deployment
  labels:
    app: backend-pruebas-deployment
spec:
  selector:
    matchLabels:
      app: backend-pruebas-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-pruebas-deployment
    spec:
      containers:
        - name: topeducation-cuotas-mysql
          image: alexmk2/topeducation-cuotas-mysql:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://backend-config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://backend-eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: MYSQL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: MYSQL_DB_HOST
            - name: MYSQL_DB_PRUEBAS
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: MYSQL_DB_PRUEBAS
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-pruebas-service
  labels:
    app: backend-pruebas-service
spec:
  selector:
    app: backend-pruebas-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer